dorm/dorm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'dorm.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('dormitory.url'))
]

dorm/dormitory/models.py
from django.db import models
from django.contrib.auth.models import User

class BunkManager(models.Manager):
    def get_available(self):
        used = Student.objects.values_list('bunk', flat=True)
        bunks = self.all()
        obj = []
        for bunk in bunks:
            if bunk.id not in used:
                obj.append((bunk.id, bunk.code))
        return obj

    def get_available2(self, using):
        used = Student.objects.values_list('bunk', flat=True)
        bunks = self.all()
        obj = []
        for bunk in bunks:
            if bunk.id not in used or bunk.id == using:
                obj.append((bunk.id, bunk.code))     
        return obj

# Create your models here.
class Bunk(models.Model):
    code = models.CharField(max_length=12, unique=True)

    objects = BunkManager()
    def __str__(self):
        return self.code

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    course = models.CharField(max_length=32)
    contact_no = models.CharField(max_length=16, verbose_name="Contact Number")
    birth_date = models.DateField(null=True, blank=True)
    mother_name = models.CharField(max_length=64)
    mother_contact = models.CharField(max_length=16, verbose_name="Contact Number")
    father_name = models.CharField(max_length=64)
    father_contact = models.CharField(max_length=16, verbose_name="Contact Number")
    guardian_name = models.CharField(max_length=64)
    guardian_contact = models.CharField(max_length=16, verbose_name="Contact Number")
    bunk = models.OneToOneField(Bunk)

    def __str__(self):
        name = "{} {}".format(self.user.first_name, self.user.last_name)
        return name

class Log(models.Model):
    student = models.ForeignKey(Student)
    log_type = models.CharField(max_length=4)
    datetime = models.DateTimeField(auto_now=False)
    destination = models.CharField(max_length=120, blank=True, null=True)

dorm/dormitory/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm

class StudentForm(forms.Form):
    username = forms.CharField(max_length=32, required=True)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=32, required=True)
    last_name = forms.CharField(max_length=32, required=True)
    course = forms.CharField(max_length=32, required=True)
    contact_no = forms.CharField(max_length=32, required=True)
    birth_date = forms.DateField()
    mother_name = forms.CharField(label = 'Mother name', max_length = 120)
    mother_contact = forms.RegexField(label = "Mother contact Number", help_text = "Accepted Formats: '+999999999'. Up to 15 digits allowed.", regex = r'^\+?1?\d{9,15}$' )
    father_name = forms.CharField(label = 'Father name', max_length = 120)
    father_contact = forms.RegexField(label = "Father contact Number", help_text = "Accepted Formats: '+999999999'. Up to 15 digits allowed.", regex = r'^\+?1?\d{9,15}$' )
    guardian_name = forms.CharField(label = 'Guardian name', max_length = 120)
    guardian_contact = forms.RegexField(label = "Guardian contact Number", help_text = "Accepted Formats: '+999999999'. Up to 15 digits allowed.", regex = r'^\+?1?\d{9,15}$' )
    bunk = forms.ChoiceField()

class UserForm(forms.Form):
    username = forms.CharField(max_length=32, required=True)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    first_name = forms.CharField(max_length=32, required=True)
    last_name = forms.CharField(max_length=32, required=True)

class BunkForm(forms.Form):
    code = forms.CharField(max_length=12, required=True)

dorm/dormitory/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
import datetime
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages

# Create your views here.
@login_required
def index(request):
    is_manager = request.user.groups.filter(name="manager").exists()
    is_student = request.user.groups.filter(name="student").exists()
    is_admin= request.user.groups.filter(name="admin").exists()
    return render(request, 'index.html', {'is_manager':is_manager, 'is_student': is_student, 'is_admin': is_admin})

@login_required
def list_admins(request):
    admins = User.objects.filter(groups__name='admin')
    return render(request, 'admin_list.html', {"admins": admins})

@login_required
def add_admin(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            user = User(
                username = clean['username'],
                first_name = clean['first_name'],
                last_name = clean['last_name'],
                email = clean['email'],
                password = clean['password'],
            )
            try:
                user.save()
                user.set_password(user.password)
                user.save()
                g = Group.objects.get(name='admin')
                g.user_set.add(user)
            except:
                messages.warning(request, "An error occured while saving. Make sure username and email address are unique")
                return HttpResponseRedirect(reverse('list_admins'))
            messages.success(request, "A new admin has been created.")
            return HttpResponseRedirect(reverse('list_admins'))
        else:
            messages.warning(request, "Error on form values.")
            return render(request, 'user_form.html', {'form': form} )
    else:
        form = UserForm()
    return render(request, 'user_form.html', {'form': form} )

def admin_profile(request, username):
    profile = User.objects.get(username=username)
    return render(request, 'admin_profile.html', {'profile': profile} )

def edit_admin_profile(request, username):
    user = User.objects.get(username=username)
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            user.username = clean['username']
            user.first_name = clean['first_name']
            user.last_name = clean['last_name']
            user.email = clean['email']
            user.set_password(clean['password'])
            try:
                user.save()
            except:
                messages.warning(request, "An error occured while saving. Make sure email address are unique")
                return HttpResponseRedirect(reverse('list_admins'))
            messages.success(request, "Admin profile updated.")
            return HttpResponseRedirect(reverse('list_admins'))
        else:
            messages.warning(request, "Error on form values.")
            return render(request, 'user_form.html', {'form': form})
    else:
        form = UserForm(initial={
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'password': user.password
        })
        form.fields['username'].widget.attrs['readonly'] = True
    return render(request, 'user_form.html', {'form': form})


def delete_admin(request, username):
    user = User.objects.get(username=username)
    user.delete()
    messages.success(request, "Success: An admin has been removed")
    return HttpResponseRedirect(reverse('list_admins'))

# Bunks
@login_required
def list_bunks(request):
    bunks = Bunk.objects.all()
    return render(request, 'bunk_list.html', {'bunks': bunks})

@login_required
def add_bunk(request):
    if request.method == "POST":
        form = BunkForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            bunk = Bunk(code=clean['code'])
            try:
                bunk.save()
            except:
                messages.warning(request, "An error occured while saving. Make sure code is unique")
                return HttpResponseRedirect(reverse('list_bunks'))
            messages.success(request, "Success: A bunk bed has been added")
            return HttpResponseRedirect(reverse('list_bunks'))
        else:
            return render(request, 'bunkform.html', {'form': form})
    else:
        form = BunkForm()
        return render(request, 'bunkform.html', {'form': form})

@login_required
def bunk(request, id):
    bunk = Bunk.objects.get(id=id)
    return render(request, 'bunk.html', {'bunk': bunk} )

@login_required
def edit_bunk(request, id):
    bunk = Bunk.objects.get(id=id)
    if request.method == "POST":
        form = BunkForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            bunk.code = clean['code']
            try:
                bunk.save()
            except:
                messages.warning(request, "An error occured while saving. Make sure code is unique")
                return HttpResponseRedirect(reverse('list_bunks'))
            messages.success(request, "Success: A bunk bed has been edited")
            return HttpResponseRedirect(reverse('list_bunks'))
        else:
            messages.warning(request, "An error in the form fields")
            return render(request, 'bunkform.html', {'form': form})
    else:
        form = BunkForm(initial={'code': bunk.code})
    return render(request, 'bunkform.html', {'form': form})

@login_required
def delete_bunk(request, id):
    bunk = Bunk.objects.get(id=id)
    bunk.delete()
    messages.success(request, "Success: A bunk bed has been removed")
    return HttpResponseRedirect(reverse('list_bunks'))

# Manager
@login_required
def list_managers(request):
    managers = User.objects.filter(groups__name='manager')
    return render(request, 'manager_list.html', {'managers': managers})

@login_required
def add_manager(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            user = User(
                username = clean['username'],
                first_name = clean['first_name'],
                last_name = clean['last_name'],
                email = clean['email'],
                password = clean['password'],
            )
            try:
                user.save()
                user.set_password(user.password)
                user.save()
                g = Group.objects.get(name='manager')
                g.user_set.add(user)
                messages.success(request, "A new manager has been created.")
            except:
                messages.warning(request, "An error occured while saving. Make sure username and email address are unique")
            return HttpResponseRedirect(reverse('list_managers'))
        else:
            messages.warning(request, "Error on form values.")
            return render(request, 'user_form.html', {'form': form} )
    else:
        form = UserForm()
    return render(request, 'user_form.html', {'form': form} )

@login_required
def manager_profile(request, username):
    profile = User.objects.get(username=username)
    return render(request, 'manager_profile.html', {'profile': profile} )

@login_required
def edit_manager_profile(request, username):
    user = User.objects.get(username=username)
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            clean = form.clean()
            user.username = clean['username']
            user.first_name = clean['first_name']
            user.last_name = clean['last_name']
            user.email = clean['email']
            user.set_password(clean['password'])
            try:
                user.save()
                messages.success(request, "Success: A manager profile has been edited")
            except:
                messages.warning(request, "An error occured while saving.")
            return HttpResponseRedirect(reverse('list_managers'))
        else:
            messages.warning(request, "An error in the form fields")
            return render(request, 'user_form.html', {'form': form})
    else:
        form = UserForm(initial={
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'email': user.email,
        'password': user.password
        })
        form.fields['username'].widget.attrs['readonly'] = True
    return render(request, 'user_form.html', {'form': form})

@login_required
def delete_manager(request, username):
    user = User.objects.get(username=username)
    user.delete()
    messages.success(request, "Success: A manager has been removed")
    return HttpResponseRedirect(reverse('list_managers'))

@login_required
def list_students(request):
    students = Student.objects.all()
    return render(request, 'student_list.html', {'students': students})

@login_required
def add_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        form.fields['bunk'].choices=Bunk.objects.get_available()
        if form.is_valid():
            clean = form.clean()
            user = User(
                username = clean['username'],
                first_name = clean['first_name'],
                last_name = clean['last_name'],
                email = clean['email'],
                password = clean['password'],
            )
            try:
                user.save()
                user.set_password(user.password)
                user.save()
                g = Group.objects.get(name='student')

dorm/dormitory/templates/base.html
<html>
    <head>
        <title>{{title}}</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
        <style>
            .app-btn {
                background-color: rgba(52, 73, 94,1.0);
                color: rgba(236, 240, 241,1.0);
                text-align: center;
                font-size: 18px;
            }
            .app-glyp {
                font-size: 48px;
                margin-top: 20px
            }
            #app-title {
                color: rgba(52, 73, 94,1.0)
            }
            table {
                 background-color: white;
                 color:rgba(52, 73, 94,1.0);
            }
        </style>
    </head>
    <body style="background-color: rgba(192, 57, 43,.20); min-width: 1200px">
        <div class="container-fluid">
            <div class="row" style="background-color: #c0392b; min-height:80px">
                <div class="col-xs-12" style='margin-left: 50px'>
                    <a href="{% url 'index' %}">
                        <h1 style="color: #f1c40f; margin: 10px 0px 0px 0px"><span class="glyphicon glyphicon-home"></span> University Dormitory Information System</h1>
                    </a>
                    <small style="color: #ecf0f1; margin: 0px 0px 0px 50px" class="lead">
                        {% if request.user.first_name %}
                            Welcome, {{request.user.first_name | title }} {{request.user.last_name | title }}
                        {% else %}
                            Welcome
                        {% endif %}
                    </small>
                </div>
            </div>
            <div class="row">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

dorm/dormitory/templates/bunk.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:300px">
    <h1 id="app-title">Bunk</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Code</td>
            <td>{{bunk.code | title}}</td>
        </tr>
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning btn-md" role="button" href="{% url 'edit_bunk' bunk.id %}">Edit Bunk</a>
        <a class="btn btn-warning btn-md" role="button" href="{% url 'delete_bunk' bunk.id %}">Delete</a>
        <a class="btn btn-warning btn-md" role="button" href="{{request.META.HTTP_REFERER}}">Back</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/bunk_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:300px">
    <h1 id="app-title">Bunks</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Code</th>
        </tr>
        {% for bunk in bunks %}
            <tr>
                <td><a href="{% url 'bunk' bunk.id %}">{{bunk.code}}</a></td>
            </tr>
        {% endfor %}
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{% url 'add_bunk' %}">Add Bunk</a>
        <a class="btn btn-warning" role="button" href="{% url 'index' %}">Back to main page</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/bunkform.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% bootstrap_messages %}
<div class="row" style="margin-left:50px; max-width:400px">
    <h1 id="app-title">Add a bunk bed</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="pull-right" style="margin-bottom: 10px">
            <a class="btn btn-warning" role="button" href="{% url 'list_bunks' %}">Cancel</a>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
    </form>
</div>
{% endblock %}

dorm/dormitory/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="row" style="margin-left:50px">
        <div class="col-xs-12">
            <h2 style="color: rgba(44, 62, 80,1.0)">
                {% if request.user.is_superuser %}Superuser{% endif%}
                {% if is_manager %}Dorm Manager{% endif%}
                {% if is_student %}Student{% endif %}
                {% if is_admin %}Administrator{% endif %} Dashboard
            </h2>
        </div>
    </div>
    <div class="row" style="margin-left:50px">
        {% if request.user.is_superuser %}
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'list_admins' %}">
                <p class="glyphicon glyphicon-user app-glyp"></p>
                <p>View Administrators</p>
            </a>
        </div>
        {% endif %}
        {% if is_admin %}
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'list_managers' %}">
                <p class="glyphicon glyphicon-user app-glyp"></p>
                <p>View Dorm Managers</p>
            </a>
        </div>
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'list_bunks' %}">
                <p class="glyphicon glyphicon-bed app-glyp"></p>
                <p>View Bunks</p>
            </a>
        </div>
        {% endif %}
        {% if is_manager %}
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'list_students' %}">
                <p class="glyphicon glyphicon-user app-glyp"></p>
                <p>View Students</p>
            </a>
        </div>
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'logs' %}">
                <p class="glyphicon glyphicon-list app-glyp"></p>
                <p>View Logs</p>
            </a>
        </div>
        {% endif %}
        {% if is_student %}
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'my_profile' request.user.username %}">
                <p class="glyphicon glyphicon-user app-glyp"></p>
                <p>View my profile</p>
            </a>
        </div>
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'my_logs' request.user.username %}">
                <p class="glyphicon glyphicon-list app-glyp"></p>
                <p>View my logs</p>
            </a>
        </div>
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'my_in' request.user.username  %}">
                <p class="glyphicon glyphicon-arrow-down app-glyp"></p>
                <p>Log in</p>
            </a>
        </div>
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'my_out' request.user.username %}">
                <p class="app-glyp glyphicon glyphicon-arrow-up"></p>
                <p>Log out</p>
            </a>
        </div>
        {% endif %}
        <div class="col-xs-2">
            <a class="thumbnail app-btn" href="{% url 'logout'%}">
                <p class="glyphicon glyphicon-remove app-glyp"></p>
                <p>Exit</p>
            </a>
        </div>
        {% if is_student %}
        <div class="col-xs-12">
            <p style="font-size: 64px; color:rgba(52, 73, 94,1.0)" id="datetime"></p>
        </div>
        {% endif %}
    </div>
{% endblock %}

dorm/dormitory/templates/logs.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">Logs</h1>
    <table  class="table table-bordered table-striped">
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Name</th>
            <th>Type</th>
            <th>Destination</th>
        </tr>
        {% for log in logs %}
            <tr>
                <td>{{log.datetime|date:"DATE_FORMAT"}}</td>
                <td>{{log.datetime|time:"P"}}</td>
                <td><a href="{% url 'student_profile' log.student.user.username %}">{{log.student.user.first_name}} {{log.student.user.last_name}}</a></td>
                <td>{{log.log_type}}</td>
                <td>{{log.destination}}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{% url 'list_students' %}">Back</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/manager_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">Managers</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Name</th>
            <th>Email Address</th>
            <th></th>
        </tr>
        {% for manager in managers %}
            <tr>
                <td>{{manager.first_name}} {{manager.last_name}}</td>
                <td>{{manager.email}}</td>
                <td><a href="{% url 'manager_profile' manager.username %}">View profile</a></td>
            </tr>
        {% endfor %}
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{% url 'add_manager' %}">Add Manager</a>
        <a class="btn btn-warning" role="button" href="{% url 'index' %}">Back to main page</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/manager_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">Manager Profile</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Name</td>
            <td>{{profile.first_name}} {{profile.last_name}}</td>
        </tr>
        <tr>
            <td>Username</td>
            <td>{{profile.username}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{profile.email}}</td>
        </tr>
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{% url 'edit_manager_profile' profile.username %}">Edit profile</a>
        <a class="btn btn-warning" role="button" href="{% url 'delete_manager' profile.username %}">Delete</a>
        <a class="btn btn-warning" role="button" href="{% url 'list_managers' %}">Back</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/my_in.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">Login to Dormitory</h1>
    <h2 id="app-title">Date and time now: <span id="datetimenow"></span></h2>
    <form method="post">
        {% csrf_token %}
        <a class="btn btn-warning btn-lg" role="button" href="{{request.META.HTTP_REFERER}}">Back</a>
        <input class="btn btn-primary btn-lg" type="submit" value="Log In">
    </form>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script>
    var d = moment().format('LT');
    document.getElementById("datetimenow").innerHTML = d;
</script>
{% endblock %}

dorm/dormitory/templates/my_out.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">Logout</h1>
    <h2 id="app-title">Date and time now: <span id="datetimenow"></span></h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="destination">Your destination</label>
            <input type="text" class="form-control" id="destination" name="destination">
        </div>
        <a class="btn btn-warning btn-lg" role="button" href="{{request.META.HTTP_REFERER}}">Back</a>
        <input class="btn btn-primary btn-lg" type="submit" value="Log out" />
    </form>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script>
    var d = moment().format('LT');
    document.getElementById("datetimenow").innerHTML = d;
</script>
{% endblock %}

dorm/dormitory/templates/my_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:500px">
    <h1 id="app-title">My profile</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <td>Name</td>
            <td>{{student.user.first_name}} {{student.user.last_name}}</td>
        </tr>
        <tr>
            <td>Username</td>
            <td>{{student.user.username}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{student.user.email}}</td>
        </tr>
        <tr>
            <td>Course</td>
            <td>{{student.course}}</td>
        </tr>
        <tr>
            <td>Contact No</td>
            <td>{{student.contact_no}}</td>
        </tr>
        <tr>
            <td>Date of birth</td>
            <td>{{student.birth_date}}</td>
        </tr>
        <tr>
            <td>Mother's name</td>
            <td>{{student.mother_name}}</td>
        </tr>
        <tr>
            <td>Mother's contact info</td>
            <td>{{student.mother_contact}}</td>
        </tr>
        <tr>
            <td>Father's name</td>
            <td>{{student.father_name}}</td>
        </tr>
        <tr>
            <td>Father's contact info</td>
            <td>{{student.father_contact}}</td>
        </tr>
        <tr>
            <td>Guardian's name</td>
            <td>{{student.guardian_name}}</td>
        </tr>
        <tr>
            <td>Guardian's contact info</td>
            <td>{{student.guardian_contact}}</td>
        </tr>
        <tr>
            <td>Assigned Bunk Bed</td>
            <td>{{student.bunk.code}}</td>
        </tr>
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{{request.META.HTTP_REFERER}}">Back</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/student_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% bootstrap_messages %}
<div class="row" style="margin-left:50px; max-width:400px">
    <h1 id="app-title">Student Form</h1>
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="pull-right" style="margin-bottom: 10px">
            <a class="btn btn-warning" role="button" href="{% url 'list_students' %}">Cancel</a>
            <input class="btn btn-primary" type="submit" value="Save" />
        </div>
    </form>
</div>
<script>
$('#id_birth_date').datepicker({
    format: 'mm/dd/yyyy'
});
</script>
{% endblock %}

dorm/dormitory/templates/student_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">List of students</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Name</th>
            <th>Email Address</th>
            <th>Bunk assigment</th>
            <th></th>
        </tr>
        {% for student in students %}
            <tr>
                <td>{{student.user.first_name}} {{student.user.last_name}}</td>
                <td>{{student.user.email}}</td>
                <td>{{student.bunk.code}}</td>
                <td><a href="{% url 'student_profile' student.user.username %}">View profile</a></td>
            </tr>
        {% endfor %}
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{% url 'add_student' %}">Add student</a>
        <a class="btn btn-warning" role="button" href="{% url 'index' %}">Back to main page</a>
    </div>
</div>
{% endblock %}

dorm/dormitory/templates/student_logs.html
{% extends 'base.html' %}
{% block content %}
<div class="row" style="margin-left:50px; max-width:600px">
    <h1 id="app-title">{{user.first_name}} {{user.last_name}}'s Logs</h1>
    <table class="table table-bordered table-striped">
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Type</th>
            <th>Destination</th>
        </tr>
        {% for log in logs %}
            <tr>
                <td>{{log.datetime|date:"DATE_FORMAT"}}</td>
                <td>{{log.datetime|time:"P"}}</td>
                <td>{{log.log_type}}</td>
                <td>{{log.destination}}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="pull-right" style="margin-bottom: 10px">
        <a class="btn btn-warning" role="button" href="{{request.META.HTTP_REFERER}}">Back</a>
    </div>
</div>
{% endblock %}